### ISSUE TITLE
Typo: Collaboratsion -> Collaboration

### ISSUE THREAD

**Issue by sbathgate** [bcgov/ExchangeLabOps#63]
**Please identify the location of the content you would like changed (line number in markdown):**
This typo can be found in the sub menu for Tools found here [here](https://bcgov.github.io/ExchangeLabOps/tools)

I took a quick peek through the code and I believe the following [line](https://github.com/bcgov/ExchangeLabOps/blame/master/pages/tools.md#L11) is the troublemaker.

**Proposed change:**
Update Collaboratsion to the intended title Collaboration :)

**Comment by HeatherRemacle** [comment]
Thanks so much for pointing this one out!

**Comment by sbathgate** [comment]
No problem, happy to help!
